### ISSUE TITLE
Compile error in linux_kernel

### ISSUE THREAD

**Issue by caedmon-kitty** [smuellerDD/leancrypto#2]
Looks like during the rename of symkmac_test.c the Kbuild file was not updated.
cd linux_kernel
make
<...>
make[2]: *** No rule to make target '/home/michaelr/unpack/entropy/git/leancrypto/linux_kernel/../aead/tests/symkmac_test.o', needed by '/home/michaelr/unpack/entropy/git/leancrypto/linux_kernel/symkmac_test.o'.  Stop.

Based on the commit to rename symkmac_test.c this is what I came up with as the fix:
diff --git a/linux_kernel/Kbuild b/linux_kernel/Kbuild
index 0f86410..ee9dc77 100644
--- a/linux_kernel/Kbuild
+++ b/linux_kernel/Kbuild
@@ -370,7 +370,7 @@ leancrypto-$(CONFIG_LEANCRYPTO_SYMKMAC_CRYPT)                                       \
                                += ../aead/src/symkmac.o
 ifdef CONFIG_LEANCRYPTO_SYMKMAC_CRYPT
 obj-m                          += symkmac_test.o
-symkmac_test-y                 += ../aead/tests/symkmac_test.o
+symkmac_test-y                 += ../aead/tests/symkmac256_test.o
 endif

 leancrypto-$(CONFIG_LEANCRYPTO_HASH_CRYPT)                                    \

Compiles OK.  Have not tested yet.

**Comment by smuellerDD** [comment]
Am Mittwoch, 28. Juni 2023, 01:30:53 CEST schrieb caedmon-kitty:

Hi caedmon,

> Looks like during the rename of symkmac_test.c the Kbuild file was not
> updated. cd linux_kernel
> make
> <...>
> make[2]: *** No rule to make target
> '/home/michaelr/unpack/entropy/git/leancrypto/linux_kernel/../aead/tests/sy
> mkmac_test.o', needed by
> '/home/michaelr/unpack/entropy/git/leancrypto/linux_kernel/symkmac_test.o'.
>  Stop.
> 
> Based on the commit to rename symkmac_test.c this is what I came up with as
> the fix: diff --git a/linux_kernel/Kbuild b/linux_kernel/Kbuild
> index 0f86410..ee9dc77 100644
> --- a/linux_kernel/Kbuild
> +++ b/linux_kernel/Kbuild
> @@ -370,7 +370,7 @@ leancrypto-$(CONFIG_LEANCRYPTO_SYMKMAC_CRYPT)           
>                            \ += ../aead/src/symkmac.o
>  ifdef CONFIG_LEANCRYPTO_SYMKMAC_CRYPT
>  obj-m                          += symkmac_test.o
> -symkmac_test-y                 += ../aead/tests/symkmac_test.o
> +symkmac_test-y                 += ../aead/tests/symkmac256_test.o
>  endif

Thanks for the note, I fixed albeit a bit differently considering that there 
are 2 symkmac tests.

The KOs now work as intended:

sudo insmod leancrypto.ko
for i in *.ko; do sudo insmod $i; done

And then check dmesg.
> 
>  leancrypto-$(CONFIG_LEANCRYPTO_HASH_CRYPT)                                 
>   \
> 
> Compiles OK.  Have not tested yet.


Ciao
Stephan
