### ISSUE TITLE
Support for RISC-32

### ISSUE THREAD

**Issue by yellowlight** [smuellerDD/leancrypto#5]
Hi Stephan,

When I use cmake to cross compile this code to risc-v32 platform and run test code, but test results are not consistent with its expected result.
Do you have some idea about this?

**Comment by smuellerDD** [comment]
Am Samstag, 31. August 2024, 09:28:41 MESZ schrieb yellowlight:

Hi yellowlight,

> Hi Stephan,
> 
> When I use cmake to cross compile this code to risc-v32 platform and run
> test code, but test results are not consistent with its expected result. Do
> you have some idea about this?

I wish I had a RISC32 system at my disposal, but I do not - also at the 
OpenSUSE build service, I was not able to find one. So, I was never able to 
test it on such a platform.

But if you are willing to help, I certainly can see to make sure it works on 
RISC32.

For that, I would like to ask you:

1. please give me an output of the command `meson test -C build` to get the 
list of algos that fail.

2. at least for one of the failure, can you please manually invoke the failing 
command shown by meson and send its output to me?

Ciao
Stephan

**Comment by yellowlight** [comment]
I just used the 'hash' module, use cmake to build, the excute sha3-256_tester.c on risc-v32 machine.
The CMakelist.txt in 'hash' module is following:
list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha256.c)
list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha512.c)
list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/hash.c)
list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/cshake.c)
list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_c.c)
list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_selector.c)
list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_selftest.c)

list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_avx2_null.c)
list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_avx512_null.c)
list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_arm_neon_null.c)
list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_arm_asm_null.c)
list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_arm_ce_null.c)
# list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_riscv_asm_null.c)
list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_riscv_asm.c)
# list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/asm/riscv32/keccakf1600.c)
list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/asm/riscv32/keccakf1600_asm.S)
list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/tests/sha3-256_tester.c)

The output runing on risc-v machine is like this:

hash ctx lc_sha3_256_riscv_asm (accelerated implementation) len 232
Expected SHA3-256 0xf1 0x6e 0x66 0xc0 0x43 0x72 0xb4 0xa3 0xe1 0xe3 0x2e 0x07 0xc4 0x1c 0x03 0x40 0x8a 0xd5 0x43 0x86 0x8c 0xc4 0x0e 0xc5 0x5e 0x00 0xbb 0xbb 0xbd 0xf5 0x91 0x1e Actual SHA3-256 0x29 0x69 0xcb 0x57 0x6f 0xa2 0xfb 0x32 0x71 0x4c 0x8d 0x5e 0x0e 0x4c 0x1b 0x48 0xe6 0x13 0x11 0xc2 0x3b 0x41 0x9a 0xfe 0xa2 0x8c 0xc5 0x37 0x27 0x53 0x63 0xc3 Expected SHA3-256 0xf1 0x6e 0x66 0xc0 0x43 0x72 0xb4 0xa3 0xe1 0xe3 0x2e 0x07 0xc4 0x1c 0x03 0x40 0x8a 0xd5 0x43 0x86 0x8c 0xc4 0x0e 0xc5 0x5e 0x00 0xbb 0xbb 0xbd 0xf5 0x91 0x1e Actual SHA3-256 0x29 0x69 0xcb 0x57 0x6f 0xa2 0xfb 0x32 0x71 0x4c 0x8d 0x5e 0x0e 0x4c 0x1b 0x48 0xe6 0x13 0x11 0xc2 0x3b 0x41 0x9a 0xfe 0xa2 0x8c 0xc5 0x37 0x27 0x53 0x63 0xc3 Expected SHA3-256 0xf1 0x6e 0x66 0xc0 0x43 0x72 0xb4 0xa3 0xe1 0xe3 0x2e 0x07 0xc4 0x1c 0x03 0x40 0x8a 0xd5 0x43 0x86 0x8c 0xc4 0x0e 0xc5 0x5e 0x00 0xbb 0xbb 0xbd 0xf5 0x91 0x1e Actual SHA3-256 0x29 0x69 0xcb 0x57 0x6f 0xa2 0xfb 0x32 0x71 0x4c 0x8d 0x5e 0x0e 0x4c 0x1b 0x48 0xe6 0x13 0x11 0xc2 0x3b 0x41 0x9a 0xfe 0xa2 0x8c 0xc5 0x37 0x27 0x53 0x63 0xc3 lc_sha3_256_riscv_asm result: 7

**Comment by smuellerDD** [comment]
Am Montag, 2. September 2024, 04:29:15 MESZ schrieb yellowlight:

Hi yellowlight,

> I just used the 'hash' module, use cmake to build, the excute
> sha3-256_tester.c on risc-v32 machine. The CMakelist.txt in 'hash' module
> is following:
> list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha256.c)
> list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha512.c)
> list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/hash.c)
> list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/cshake.c)
> list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_c.c)
> list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_selector.c)
> list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_selftest.c)
> 
> list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_avx2_null.c)
> list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_avx512_null.c)
> list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_arm_neon_null.c)
> list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_arm_asm_null.c)
> list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_arm_ce_null.c)
> # list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_riscv_asm_null.c)
> list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/sha3_riscv_asm.c) #
> list(APPEND SUB_DIR
> ${CMAKE_CURRENT_SOURCE_DIR}/src/asm/riscv32/keccakf1600.c) list(APPEND
> SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/asm/riscv32/keccakf1600_asm.S)
> list(APPEND SUB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/tests/sha3-256_tester.c)
> 
> The output runing on risc-v machine is like this:
> 
> hash ctx lc_sha3_256_riscv_asm (accelerated implementation) len 232
> Expected SHA3-256 0xf1 0x6e 0x66 0xc0 0x43 0x72 0xb4 0xa3 0xe1 0xe3 0x2e
> 0x07 0xc4 0x1c 0x03 0x40 0x8a 0xd5 0x43 0x86 0x8c 0xc4 0x0e 0xc5 0x5e 0x00
> 0xbb 0xbb 0xbd 0xf5 0x91 0x1e Actual SHA3-256 0x29 0x69 0xcb 0x57 0x6f 0xa2
> 0xfb 0x32 0x71 0x4c 0x8d 0x5e 0x0e 0x4c 0x1b 0x48 0xe6 0x13 0x11 0xc2 0x3b
> 0x41 0x9a 0xfe 0xa2 0x8c 0xc5 0x37 0x27 0x53 0x63 0xc3 Expected SHA3-256
> 0xf1 0x6e 0x66 0xc0 0x43 0x72 0xb4 0xa3 0xe1 0xe3 0x2e 0x07 0xc4 0x1c 0x03
> 0x40 0x8a 0xd5 0x43 0x86 0x8c 0xc4 0x0e 0xc5 0x5e 0x00 0xbb 0xbb 0xbd 0xf5
> 0x91 0x1e Actual SHA3-256 0x29 0x69 0xcb 0x57 0x6f 0xa2 0xfb 0x32 0x71 0x4c
> 0x8d 0x5e 0x0e 0x4c 0x1b 0x48 0xe6 0x13 0x11 0xc2 0x3b 0x41 0x9a 0xfe 0xa2
> 0x8c 0xc5 0x37 0x27 0x53 0x63 0xc3 Expected SHA3-256 0xf1 0x6e 0x66 0xc0
> 0x43 0x72 0xb4 0xa3 0xe1 0xe3 0x2e 0x07 0xc4 0x1c 0x03 0x40 0x8a 0xd5 0x43
> 0x86 0x8c 0xc4 0x0e 0xc5 0x5e 0x00 0xbb 0xbb 0xbd 0xf5 0x91 0x1e Actual
> SHA3-256 0x29 0x69 0xcb 0x57 0x6f 0xa2 0xfb 0x32 0x71 0x4c 0x8d 0x5e 0x0e
> 0x4c 0x1b 0x48 0xe6 0x13 0x11 0xc2 0x3b 0x41 0x9a 0xfe 0xa2 0x8c 0xc5 0x37
> 0x27 0x53 0x63 0xc3 lc_sha3_256_riscv_asm result: 7

Yes, leancrypto does have the asm code for RISC32 hashing included, but it is 
explicitly disabled in hash/src/meson.build starting at line 104, because I 
have not been able to test its correctness.

But looking at the code above, you seem to have defined your own CMakelist.txt 
and thus do not use the meson build system. Thus, I would suggest you follow 
the meson build system settings to not enable it unless I was able to verify 
the code.


Ciao
Stephan

**Comment by smuellerDD** [comment]
If there is an issue for leancrypto, please reopen
