### ISSUE TITLE
Difference between leancrypto and Kernel asymmetric crypto interface for signature verify

### ISSUE THREAD

**Issue by kamlesh0hrs** [smuellerDD/leancrypto#7]
Hi Stephan,

leancrypto Dilithium's signature verification (Kernel) initializes two different scatterlist ( for akcipher_request_set_crypt ) for source and destination buffer.
This seems a bit different than the existing Linux Kernel aysmmetric signature verification function where it initiates a scatterlist table and pass it as source.

Do you think its worth making leancrypto signature verification function to take actterlist table and operate on that which will be in sync with the Kernel's exiting interface ?

This way if someone wants to use it in Kernel then they need to do only minimal changes in code taken from upstream Kernel. 
Obiously one can easily modify Kernel or leancrypto code as per their requirement but just wanted your thought on this.

Thanks,
Kamlesh

**Comment by smuellerDD** [comment]
Am Samstag, 28. September 2024, 08:41:17 MESZ schrieb kamlesh0hrs:

Hi kamlesh0hrs,

> Hi Stephan,
> 
> leancrypto Dilithium's signature verification (Kernel) initializes two
> different scatterlist ( for akcipher_request_set_crypt ) for source and
> destination buffer. This seems a bit different than the existing Linux
> Kernel aysmmetric signature verification function where it initiates a
> scatterlist table and pass it as source.
> 
> Do you think its worth making leancrypto signature verification function to
> take actterlist table and operate on that which will be in sync with the
> Kernel's exiting interface ?

Absolutely. Thanks for pointing that out. I should have looked before I design 
my own SGL structure :-)
> 
> This way if someone wants to use it in Kernel then they need to do only
> minimal changes in code taken from upstream Kernel. Obiously one can easily
> modify Kernel or leancrypto code as per their requirement but just wanted
> your thought on this.
> 

Fixed, for both ML-DSA and SLH-DSA.

> Thanks,
> Kamlesh


Ciao
Stephan
