### ISSUE TITLE
UEFI target?

### ISSUE THREAD

**Issue by xnox** [smuellerDD/leancrypto#9]
Has UEFI target been developed? Either firmware itself or just the UEFI runtime?

Thinking this might be a really nice upgrade of ancient openssl forks in rhboot/shim and EDK2.

**Comment by smuellerDD** [comment]
That is a good suggestion - leancrypto is meant to support such environments. I need to get up to speed how to compile for UEFI, and how memory is allocated (if stack-only support is not sufficient for users). If you have an example, that would expedite things.

Ciao
Stephan

—
Cui bono?

**Comment by smuellerDD** [comment]
Am Dienstag, 8. Oktober 2024, 14:34:16 MESZ schrieb Dimitri John Ledkov:

Hi Dimitri,

> For UEFI applications:
> - https://github.com/rhboot/shim
> - https://github.com/rhboot/grub2
> - https://github.com/systemd/systemd/tree/main/src/boot/efi
> 
> For EDK2:
> - https://github.com/tianocore/edk2
> 
> Note all major linux distributions have those packaged. They are non-trivial
> to build, as they all use freestanding compilers and often rewrite their
> own standard functionality.
> 
> But they do lots of cryptography to provide & support UEFI HTTPS boot for
> example, and parse/validate DER certificates and signatures. None of them
> have new enough cryptography nor post-quantum cryptography.
> 
> Replacing all of https://github.com/rhboot/shim/tree/main/Cryptlib would be
> really nice. And open the door to fixing
> https://github.com/rhboot/shim/issues/586
> 
> https://github.com/rhboot/shim/blob/main/Cryptlib/Pk/CryptAuthenticode.c is
> like the most called cryptographic operations to verify signature of the
> next stage bootloader.

Thanks for the pointers. But please note that leancrypto as of now does not 
have PKCS7 or X.509 support.

Ciao
Stephan

**Comment by xnox** [comment]
Sadness and despair.

**Comment by smuellerDD** [comment]
Am Dienstag, 8. Oktober 2024, 22:41:18 MESZ schrieb Dimitri John Ledkov:

Hi Dimitri,

> Sadness and despair.

I am planning to add it, but it is not currently there - you may want to keep 
the issue open to track it.

Ciao
Stephan

**Comment by xnox** [comment]
I am "watching" the repo and starred it as well =)

**Comment by smuellerDD** [comment]
Am Dienstag, 8. Oktober 2024, 22:44:03 MESZ schrieb Dimitri John Ledkov:

Hi Dimitri,

> I am "watching" the repo and starred it as well =)

:-)

Ciao
Stephan

**Comment by smuellerDD** [comment]
The heavy lifting of adding PKCS7 support is completed. Now I need to add test and polish it before releasing.

**Comment by smuellerDD** [comment]
PKCS7 parser added

**Comment by smuellerDD** [comment]
A X.509 certificate generator is added that creates complete PQC certificates. A full 4-way certificate chain is provided an an example.

**Comment by smuellerDD** [comment]
A full PKCS#7 support of all supported signature mechanisms including hybrid algorithms is now present. This includes a PKCS#7 parser as well as generator. See https://github.com/smuellerDD/leancrypto/tree/master/asn1/src#pkcs7-message-generator

**Comment by smuellerDD** [comment]
UEFI target is now implemented. See README or https://leancrypto.org/leancrypto/efi/index.html

The only remaining item is: testing.

With that said, I think that now the request is fully covered.
